version: '3.3'
services:
  mongo:
    image: mongo:3.4
  web:
    image: proactivehk/hackathon:master
    ports:
     - "3000:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    depends_on:
     - mongo
    # volumes:
    #  - .:/starter
    #  - /starter/node_modules
  console:
    image: debian:jessie
    tty: true

